[package]
name = "autonomic"
version = "0.1.0"
authors = ["Rowan Skewes <rowan.skewes@gmail.com>"]

[dependencies]

rand = "0.3.14"
tiny_http = "0.5"
slack-hook = "0.5"
serde_json = "1.0"
url = "1.5"
time = "0.1"
rusqlite = "0.12"
log = "0.3"
env_logger = "0.3"
curl = "0.4"
